name = "literasi-membaca-ppi19"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "literasi-membaca-ppi19"

[env.staging]
name = "literasi-membaca-ppi19-staging"
